name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: "3.12"
#      - uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-latest
    # needs: lint
    env:
      B2B_CI: 1
      DJANGO_SETTINGS_MODULE: b2broker.settings
      DJANGO_CONFIGURATION: CI
      B2B_DB_HOST: mysql
      B2B_DB_PORT: 3306
      B2B_DB_NAME: testdb
      B2B_DB_USER: root
      B2B_DB_PASSWORD: pass
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: $B2B_DB_NAME
          MYSQL_ROOT_PASSWORD: $B2B_DB_PASSWORD
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache dependencies
        id: cache-test
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements.test.txt
      - name: Run tests
        run: |
          export PYTEST_ADDOPTS="--ignore-glob=tests/functional/*"
          make test
